// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountUsers(ctx context.Context) (int64, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	DeactivateUser(ctx context.Context, id uint64) error
	DeleteExpiredRefreshTokens(ctx context.Context) error
	// We query by the hash of the token provided by the user
	GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uint64) (User, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	RevokeRefreshToken(ctx context.Context, tokenHash string) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
