package main

import (
	"context"
	"log"

	"github.com/waqasmani/go-boilerplate/cmd/api/docs" // docs is generated by Swag CLI
	"github.com/waqasmani/go-boilerplate/internal/app"
	"github.com/waqasmani/go-boilerplate/internal/config"
	"github.com/waqasmani/go-boilerplate/internal/infrastructure/database"
	"github.com/waqasmani/go-boilerplate/internal/infrastructure/observability"
)

func main() {
	// programmatically set swagger info
	docs.SwaggerInfo.Title = "Swagger Example API"
	docs.SwaggerInfo.Description = "This is a sample server Petstore server."
	docs.SwaggerInfo.Version = "1.0"
	docs.SwaggerInfo.BasePath = "/api/v1"
	cfg, err := config.Load()
	if err != nil {
		log.Fatalf("Failed to load config: %v", err)
	}

	logger, err := observability.NewLogger(cfg.Logging.Level, cfg.Logging.Encoding)
	if err != nil {
		log.Fatalf("Failed to initialize logger: %v", err)
	}
	defer logger.Sync()

	db, err := database.NewMariaDB(context.Background(), &cfg.Database)
	if err != nil {
		log.Fatalf("Failed to connect to database: %v", err)
	}

	container := app.NewContainer(cfg, db.DB, logger)
	server := app.NewServer(container)

	if err := server.Start(); err != nil {
		log.Fatalf("Server error: %v", err)
	}
}
